<?php

declare(strict_types=1);

// ============================================================
// SSAToCGenerator — SSA Module → C 代码降低（Task 15）
//
// 输入：SSAModule（已优化）
// 输出：完整 C 源代码字符串
//
// 降低规则：
//   - Phi 节点消除：在每个前驱块末尾（终结指令之前）插入复制语句
//     自引用 phi（incoming 来自当前块本身）也通过同样机制处理
//   - 块标签：block_<id>，入口块加 /* entry */ 注释
//   - 寄存器命名：SSA Value 的 name 字段去掉 $ 前缀；未命名值用 v_<id>
//     所有名称统一加 v_ 前缀以避免与 C 关键字冲突
//   - SSAType → C 类型映射：INT→int64_t, FLOAT→double, BOOL→bool,
//     PTR<void>→void*, PTR<int>→t_string* (string 内部表示),
//     ARRAY→t_array*, STRUCT→t_object*, FUNC→void*
//
// 依赖：SSA.php（数据结构）
// ============================================================

require_once __DIR__ . '/SSA.php';

class SSAToCGenerator
{
    /** 当前正在降低的函数（用于查询值表） */
    private ?SSAFunction $currentFunc = null;

    /** phi 复制缓冲：blockId => [行字符串数组]
     *  每个前驱块末尾要追加的 phi 复制语句（在终结指令之前） */
    private array $phiCopiesByBlock = [];

    public function __construct() {}

    // ═══════════════════════════════════════════════════════════════
    // 主入口
    // ═══════════════════════════════════════════════════════════════

    /**
     * 主入口：降低整个 SSAModule 为完整 C 源代码。
     *
     * @param SSAModule $module     已优化的 SSA 模块
     * @param string    $sourceFile 源文件路径（仅用于注释）
     * @return string 完整 C 源代码
     */
    public function generate(SSAModule $module, string $sourceFile = ''): string
    {
        $out = '';
        $out .= "// ============================================================\n";
        $out .= "// Generated by TinyPHP SSA → C lowering\n";
        $out .= "// Source: {$sourceFile}\n";
        $out .= "// ============================================================\n\n";
        // common.h 是总入口头文件，按正确顺序引入 types.h / array.h / runtime.h 等，
        // 避免单独 include runtime.h 时 arr_freelist_count 等符号未声明
        $out .= '#include "common.h"' . "\n\n";

        // 函数前向声明
        $out .= "// ── 函数前向声明 ──\n";
        foreach ($module->functions as $func) {
            $out .= 'static ' . $this->funcSignature($func) . ";\n";
        }
        $out .= "\n";

        // 函数定义
        foreach ($module->functions as $func) {
            $out .= $this->generateFunction($func);
            $out .= "\n";
        }

        // 如果没有 main 函数，生成默认 main 入口
        $hasMain = false;
        foreach ($module->functions as $func) {
            if ($func->name === 'main') {
                $hasMain = true;
                break;
            }
        }
        if (!$hasMain) {
            $out .= "int main(int argc, char* argv[]) {\n";
            $out .= "    tphp_rt_init();\n";
            $out .= "    return 0;\n";
            $out .= "}\n";
        }

        return $out;
    }

    // ═══════════════════════════════════════════════════════════════
    // 单函数降低
    // ═══════════════════════════════════════════════════════════════

    /**
     * 降低单个函数。
     */
    public function generateFunction(SSAFunction $func): string
    {
        $this->currentFunc = $func;
        $this->collectPhiCopies($func);

        $out = '';
        $out .= 'static ' . $this->funcSignature($func) . " {\n";

        // 收集所有 phi 结果变量声明（在 entry block 开头统一声明）
        // 原因：phi 结果在前驱块末尾被赋值，在合并块使用，
        //   C 语言要求变量先声明后使用，因此把声明放在函数顶部最简单
        $phiDecls = [];
        foreach ($func->blocks as $block) {
            foreach ($block->instructions as $inst) {
                if ($inst->op === OpCode::PHI) {
                    $type = $this->valueType($inst->dst);
                    $name = $this->valueName($inst->dst);
                    $phiDecls[] = "{$type} {$name}; /* phi result */";
                }
            }
        }

        // 按 block id 顺序输出，entry 块优先
        $blockIds = array_keys($func->blocks);
        usort($blockIds, function (int $a, int $b) use ($func) {
            if ($a === $func->entryBlockId) return -1;
            if ($b === $func->entryBlockId) return 1;
            return $a <=> $b;
        });

        foreach ($blockIds as $bid) {
            $blockOut = $this->generateBlock($func->blocks[$bid], $bid);

            // 在 entry block label 行之后插入 phi 声明
            if ($bid === $func->entryBlockId && !empty($phiDecls)) {
                $lines = explode("\n", $blockOut);
                $newLines = [$lines[0]];
                foreach ($phiDecls as $decl) {
                    $newLines[] = '    ' . $decl;
                }
                $count = count($lines);
                for ($i = 1; $i < $count; $i++) {
                    $newLines[] = $lines[$i];
                }
                $blockOut = implode("\n", $newLines);
            }
            $out .= $blockOut;
        }

        $out .= "}\n";

        $this->currentFunc = null;
        $this->phiCopiesByBlock = [];
        return $out;
    }

    // ═══════════════════════════════════════════════════════════════
    // 单块降低
    // ═══════════════════════════════════════════════════════════════

    /**
     * 降低单个基本块。
     *
     * @param SSABasicBlock $block
     * @param int           $bid   块 id（用于标签命名）
     * @return string 块的 C 代码（含标签、指令、phi 复制、终结指令）
     */
    public function generateBlock(SSABasicBlock $block, int $bid): string
    {
        $entryTag = ($this->currentFunc !== null && $bid === $this->currentFunc->entryBlockId)
            ? '  /* entry */'
            : '';
        $out = "block_{$bid}:{$entryTag}\n";

        // 分离终结指令（phi 已在 collectPhiCopies 中处理）
        $terminator = null;
        $normalInsts = [];
        foreach ($block->instructions as $inst) {
            if ($inst->op === OpCode::PHI) {
                continue;
            }
            if ($inst->op->isTerminator()) {
                $terminator = $inst;
                continue;
            }
            $normalInsts[] = $inst;
        }

        // 普通指令
        foreach ($normalInsts as $inst) {
            $line = $this->generateInstruction($inst);
            if ($line !== '') {
                $out .= '    ' . $line . "\n";
            }
        }

        // phi 复制（来自后继块的 phi 节点，需要在跳转前赋值给 phi 结果）
        // 这些复制语句是 phi 消除的核心：把 phi 的语义从合并点提升到前驱块末尾
        $copies = $this->phiCopiesByBlock[$bid] ?? [];
        foreach ($copies as $copy) {
            $out .= '    ' . $copy . "\n";
        }

        // 终结指令（RET / BR / JMP）
        if ($terminator !== null) {
            $line = $this->generateInstruction($terminator);
            if ($line !== '') {
                $out .= '    ' . $line . "\n";
            }
        }

        return $out;
    }

    // ═══════════════════════════════════════════════════════════════
    // 单指令降低
    // ═══════════════════════════════════════════════════════════════

    /**
     * 降低单条 SSA 指令为 C 语句（不含行尾换行）。
     */
    public function generateInstruction(SSAInstruction $inst): string
    {
        switch ($inst->op) {
            // ── 常量 ──
            case OpCode::CONST_INT:
                $v = $inst->extra['value'] ?? 0;
                return $this->declAssign($inst->dst, "{$v}");

            case OpCode::CONST_FLOAT:
                $v = $inst->extra['value'] ?? 0.0;
                return $this->declAssign($inst->dst, $this->formatFloat((float)$v));

            case OpCode::CONST_BOOL:
                $v = $inst->extra['value'] ?? false;
                return $this->declAssign($inst->dst, $v ? 'true' : 'false');

            case OpCode::CONST_NULL:
                return $this->declAssign($inst->dst, 'NULL');

            // ── 复制 ──
            case OpCode::COPY:
                return $this->declAssign($inst->dst, $this->valueName($inst->operands[0]));

            // ── 算术运算 ──
            case OpCode::ADD:
                return $this->declAssign($inst->dst, $this->binOp($inst, '+'));
            case OpCode::SUB:
                return $this->declAssign($inst->dst, $this->binOp($inst, '-'));
            case OpCode::MUL:
                return $this->declAssign($inst->dst, $this->binOp($inst, '*'));
            case OpCode::DIV:
                return $this->declAssign($inst->dst, $this->binOp($inst, '/'));
            case OpCode::MOD:
                return $this->declAssign($inst->dst, $this->binOp($inst, '%'));
            case OpCode::NEG:
                return $this->declAssign($inst->dst, '-' . $this->valueName($inst->operands[0]));

            // ── 比较运算（结果类型 bool）──
            case OpCode::EQ:
                return $this->declAssign($inst->dst, $this->cmpOp($inst, '=='));
            case OpCode::NE:
                return $this->declAssign($inst->dst, $this->cmpOp($inst, '!='));
            case OpCode::LT:
                return $this->declAssign($inst->dst, $this->cmpOp($inst, '<'));
            case OpCode::LE:
                return $this->declAssign($inst->dst, $this->cmpOp($inst, '<='));
            case OpCode::GT:
                return $this->declAssign($inst->dst, $this->cmpOp($inst, '>'));
            case OpCode::GE:
                return $this->declAssign($inst->dst, $this->cmpOp($inst, '>='));

            // ── 逻辑运算 ──
            case OpCode::AND:
                return $this->declAssign($inst->dst, $this->binOp($inst, '&&'));
            case OpCode::OR:
                return $this->declAssign($inst->dst, $this->binOp($inst, '||'));
            case OpCode::NOT:
                return $this->declAssign($inst->dst, '!' . $this->valueName($inst->operands[0]));

            // ── 转换 ──
            case OpCode::CAST:
                $toType = $this->mapType($inst->extra['to_type'] ?? SSAType::int());
                $v = $this->valueName($inst->operands[0]);
                return $this->declAssign($inst->dst, "({$toType}) {$v}");

            case OpCode::BITCAST:
                $toType = $this->mapType($inst->extra['to_type'] ?? SSAType::int());
                $v = $this->valueName($inst->operands[0]);
                return $this->declAssign($inst->dst, "*( {$toType}*)&{$v}");

            // ── 内存操作 ──
            case OpCode::ALLOCA:
                $type = $this->inferAllocaType($inst);
                $name = $this->valueName($inst->dst);
                return "{$type} {$name}; /* alloca */";

            case OpCode::LOAD:
                return $this->declAssign($inst->dst, '*' . $this->valueName($inst->operands[0]));

            case OpCode::STORE:
                $ptr = $this->valueName($inst->operands[0]);
                $val = $this->valueName($inst->operands[1]);
                return "*{$ptr} = {$val};";

            // ── 调用 ──
            case OpCode::CALL:
                $fn = $inst->extra['func'] ?? '?';
                $args = implode(', ', array_map(
                    fn($v) => $this->valueName($v),
                    $inst->operands,
                ));
                if ($inst->dst === null) {
                    return "{$fn}({$args});";
                }
                return $this->declAssign($inst->dst, "{$fn}({$args})");

            // ── 终结指令 ──
            case OpCode::RET:
                if (empty($inst->operands)) {
                    return 'return;';
                }
                return 'return ' . $this->valueName($inst->operands[0]) . ';';

            case OpCode::BR:
                $cond = $this->valueName($inst->operands[0]);
                $thenB = $inst->extra['then_block'] ?? -1;
                $elseB = $inst->extra['else_block'] ?? -1;
                return "if ({$cond}) goto block_{$thenB}; else goto block_{$elseB};";

            case OpCode::JMP:
                $tgt = $inst->extra['target_block'] ?? -1;
                return "goto block_{$tgt};";

            // ── Phi 节点（已在 collectPhiCopies 处理，正常降低中不应到达）──
            case OpCode::PHI:
                return '/* phi (eliminated) */';

            default:
                return '/* unhandled: ' . $inst->op->name . ' */';
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // Phi 消除
    // ═══════════════════════════════════════════════════════════════

    /**
     * 收集所有 phi 节点的复制语句，按前驱块分组。
     *
     * 对于 phi `%dst = PHI [%v1 from B1, %v2 from B2]`：
     *   - 在 B1 末尾（终结指令之前）插入 `dst = v1`
     *   - 在 B2 末尾（终结指令之前）插入 `dst = v2`
     *   - 若 B1 == B2 == 当前块（自循环），同样在块末尾插入
     *
     * @param SSAFunction $func
     */
    private function collectPhiCopies(SSAFunction $func): void
    {
        $this->phiCopiesByBlock = [];
        foreach ($func->blocks as $block) {
            foreach ($block->instructions as $inst) {
                if ($inst->op !== OpCode::PHI) {
                    continue;
                }
                $blocks = $inst->extra['blocks'] ?? [];
                $dstName = $this->valueName($inst->dst);
                foreach ($inst->operands as $i => $srcVal) {
                    $srcBlock = $blocks[$i] ?? -1;
                    if ($srcBlock < 0) {
                        continue;
                    }
                    $srcName = $this->valueName($srcVal);
                    $this->phiCopiesByBlock[$srcBlock][] = "{$dstName} = {$srcName};";
                }
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // 辅助：值与类型
    // ═══════════════════════════════════════════════════════════════

    /**
     * 获取 value id 对应的 C 变量名。
     * 命名规则：v_<name>（已去 $ 前缀）或 v_<id>（未命名值）
     */
    private function valueName(int $valueId): string
    {
        if ($this->currentFunc === null) {
            return "v_{$valueId}";
        }
        $value = $this->currentFunc->values[$valueId] ?? null;
        if ($value === null) {
            return "v_{$valueId}";
        }
        $name = $value->name;
        if ($name === null || $name === '') {
            return "v_{$valueId}";
        }
        // SSABuilder 已通过 varDisplayName 去掉 $ 前缀
        // 加 v_ 前缀避免与 C 关键字、库函数名冲突
        return 'v_' . $name;
    }

    /**
     * 获取 value id 对应的 C 类型字符串。
     */
    private function valueType(int $valueId): string
    {
        if ($this->currentFunc === null) {
            return 'int64_t';
        }
        $value = $this->currentFunc->values[$valueId] ?? null;
        if ($value === null) {
            return 'int64_t';
        }
        return $this->mapType($value->type);
    }

    /**
     * 生成 `T name = rhs;` 形式的声明赋值语句。
     * 若 dst 为 null，仅返回 `rhs;`（用于无返回值场景，理论不应发生）。
     */
    private function declAssign(?int $dst, string $rhs): string
    {
        if ($dst === null) {
            return "{$rhs};";
        }
        $type = $this->valueType($dst);
        $name = $this->valueName($dst);
        return "{$type} {$name} = {$rhs};";
    }

    /**
     * 二元算术/逻辑运算的右值构造：`a OP b`
     */
    private function binOp(SSAInstruction $inst, string $op): string
    {
        $l = $this->valueName($inst->operands[0]);
        $r = $this->valueName($inst->operands[1]);
        return "{$l} {$op} {$r}";
    }

    /**
     * 比较运算的右值构造：`(a OP b)`（带括号，确保优先级正确）
     */
    private function cmpOp(SSAInstruction $inst, string $op): string
    {
        $l = $this->valueName($inst->operands[0]);
        $r = $this->valueName($inst->operands[1]);
        return "({$l} {$op} {$r})";
    }

    /**
     * 推断 ALLOCA 指令分配变量的 C 类型。
     */
    private function inferAllocaType(SSAInstruction $inst): string
    {
        $elemType = $inst->extra['elem_type'] ?? null;
        if ($elemType instanceof SSAType) {
            // ALLOCA 分配的是数组，用元素指针类型
            return $this->mapType($elemType) . '*';
        }
        return 'int64_t';
    }

    /**
     * 格式化浮点字面量为 C 合法表示。
     * 确保包含 . 或 e，避免被 C 当作 int；bool/null 安全转换。
     */
    private function formatFloat(float $v): string
    {
        if (is_nan($v)) return 'NAN';
        if (is_infinite($v)) return $v > 0 ? 'INFINITY' : '-INFINITY';
        $s = var_export($v, true);
        // var_export 对 float 输出如 1.5, 0.0, 1.0E+20 等，已满足 C 语法
        // 若整数浮点（如 5.0）被表示为 "5.0"，可直接使用
        if (!str_contains($s, '.') && !str_contains($s, 'E') && !str_contains($s, 'e')) {
            $s .= '.0';
        }
        return $s;
    }

    // ═══════════════════════════════════════════════════════════════
    // 函数签名构造
    // ═══════════════════════════════════════════════════════════════

    /**
     * 构造函数签名（不含 static 前缀与分号）。
     *
     * 形如：`int64_t add(int64_t v_a, int64_t v_b)`
     */
    private function funcSignature(SSAFunction $func): string
    {
        $retType = $this->mapType($func->retType);
        $params = [];
        $idx = 0;
        foreach ($func->paramTypes as $i => $ptype) {
            // 参数 value id 按 0,1,2,... 顺序创建（SSABuilder.build 中）
            $value = $func->values[$i] ?? null;
            $name = $value !== null && $value->name !== null && $value->name !== ''
                ? 'v_' . $value->name
                : "v_arg{$idx}";
            $params[] = $this->mapType($ptype) . ' ' . $name;
            $idx++;
        }
        if (empty($params)) {
            return "{$retType} {$func->name}(void)";
        }
        return "{$retType} {$func->name}(" . implode(', ', $params) . ")";
    }

    // ═══════════════════════════════════════════════════════════════
    // 类型映射（公开，便于测试验证）
    // ═══════════════════════════════════════════════════════════════

    /**
     * SSAType → C 类型字符串映射。
     *
     * 映射规则：
     *   VOID   → void
     *   INT    → int64_t
     *   FLOAT  → double
     *   BOOL   → bool
     *   PTR    → 递归 pointee：
     *             PTR<void>   → void*     (相当于 null/通用指针)
     *             PTR<int>    → t_string* (TinyPHP string 内部表示)
     *             PTR<float>  → double*
     *             PTR<bool>   → bool*
     *             PTR<PTR<T>> → <T>**
     *             PTR<ARRAY>  → t_array*
     *             PTR<STRUCT> → t_object*
     *             PTR<FUNC>   → void*
     *   ARRAY  → t_array*
     *   STRUCT → t_object*
     *   FUNC   → void*
     */
    public function mapType(SSAType $t): string
    {
        return match ($t->kind) {
            SSATypeKind::VOID   => 'void',
            SSATypeKind::INT    => 'int64_t',
            SSATypeKind::FLOAT  => 'double',
            SSATypeKind::BOOL   => 'bool',
            SSATypeKind::PTR    => $this->mapPtrType($t),
            SSATypeKind::ARRAY  => 't_array*',
            SSATypeKind::STRUCT => 't_object*',
            SSATypeKind::FUNC   => 'void*',
        };
    }

    /**
     * 指针类型的细分映射。
     */
    private function mapPtrType(SSAType $t): string
    {
        $pointee = $t->pointeeType;
        if ($pointee === null) {
            return 'void*';
        }
        return match ($pointee->kind) {
            SSATypeKind::VOID   => 'void*',
            SSATypeKind::INT    => 't_string*',  // string 的内部表示（见 SSABuilder::typeFromString）
            SSATypeKind::FLOAT  => 'double*',
            SSATypeKind::BOOL   => 'bool*',
            SSATypeKind::PTR    => $this->mapType($pointee) . '*',
            SSATypeKind::ARRAY  => 't_array*',
            SSATypeKind::STRUCT => 't_object*',
            SSATypeKind::FUNC   => 'void*',
        };
    }
}
