<?php

declare(strict_types=1);

class CodeGenerator implements ASTVisitor
{
    private string $className = '';
    private int $indent = 0;

    /** 变量类型追踪：varName → className（对象）或 C 类型（基础类型） */
    private array $varTypes = [];
    /** 已声明变量集合 */
    private array $declaredVars = [];
    /** 当前作用域内的对象变量名列表（用于自动析构） */
    private array $scopeObjects = [];

    /** 字面量 → C 类型的映射 */
    private static array $litTypeMap = [
        IntLiteralExpr::class    => 't_int',
        FloatLiteralExpr::class  => 't_float',
        StringLiteralExpr::class => 't_string',
        BoolLiteralExpr::class   => 't_bool',
    ];

    private static array $typeMap = [
        'int' => 't_int', 'float' => 't_float', 'string' => 't_string',
        'bool' => 't_bool', 'void' => 'void', 'array' => 't_array*',
    ];

    /** 临时变量计数器，用于数组字面量的复合表达式 */
    private int $tmpVarCounter = 0;

    /** 闭包函数计数器 */
    private int $closureCounter = 0;
    /** 收集所有闭包函数的 C 实现，在 visitProgram 末尾统一输出 */
    private array $closureImpls = [];

    // ============================================================
    public function generate(ProgramNode $program, string $phpFile, string $outputDir): string
    {
        $this->className = $program->mainClass ? self::classCName($program->mainClass) : '';
        $this->resetState();
        $outPath = $outputDir . '/' . pathinfo($phpFile, PATHINFO_FILENAME) . '.c';
        $code = $program->accept($this);
        file_put_contents($outPath, $code);
        return $outPath;
    }

    // ============================================================
    public function visitProgram(ProgramNode $node): string
    {
        $this->indent = 0;
        $p = [];

        // Header
        $p[] = "/* Generated by TinyPHP — PHP → C (TCC) */";
        $p[] = '';
        $p[] = '#include "common.h"';
        $p[] = '';

        $allClasses = array_merge(
            $node->mainClass ? [$node->mainClass] : [],
            $node->extraClasses
        );
        $mainClassName = $node->mainClass ? self::classCName($node->mainClass) : '';

        // ── Phase 1: 所有类的 struct + 前置声明 (保证类型可见) ──
        foreach ($allClasses as $class) {
            $this->className = self::classCName($class);
            $isMain = (self::classCName($class) === $mainClassName);
            $p[] = $this->emitClassForward($class, $isMain);
        }

        // 独立函数前置声明
        foreach ($node->functions as $fn) {
            $ret = self::mapType($fn->returnType);
            $params = array_map(fn($p) => $this->visitParam($p), $fn->params);
            $p[] = 'static ' . $ret . ' tphp_' . self::funcCName($fn) . '(' . implode(', ', $params) . ');';
        }
        if ($node->functions) $p[] = '';

        // ── Phase 2: 所有类的方法实现 + allocator ──
        foreach ($allClasses as $class) {
            $this->className = self::classCName($class);
            $isMain = (self::classCName($class) === $mainClassName);
            $p[] = $this->emitClassImpl($class, $isMain);
        }

        // 独立函数实现
        foreach ($node->functions as $fn) {
            $p[] = $fn->accept($this);
            $p[] = '';
        }

        // ── 闭包函数实现（文件作用域 static 函数） ──
        if (!empty($this->closureImpls)) {
            $p[] = "/* ── 闭包函数实现 ──────────────────────────── */";
            foreach ($this->closureImpls as $impl) {
                $p[] = $impl;
                $p[] = '';
            }
        }

        // C 入口
        if ($node->mainClass !== null) {
            $this->className = self::classCName($node->mainClass);
            $p[] = $this->generateCEntry();
        }

        return implode("\n", $p) . "\n";
    }

    /** 重置状态（每次 generate 调用时） */
    private function resetState(): void
    {
        $this->varTypes = [];
        $this->declaredVars = [];
        $this->scopeObjects = [];
        $this->tmpVarCounter = 0;
        $this->closureCounter = 0;
        $this->closureImpls = [];
    }

    /** Phase 1: struct + 前置声明 */
    private function emitClassForward(ClassNode $class, bool $isMain): string
    {
        $cn = self::classCName($class);
        $ctor = $dtor = null;
        $methods = [];
        foreach ($class->methods as $m) {
            if ($m->name === '__construct') $ctor = $m;
            elseif ($m->name === '__destruct') $dtor = $m;
            else $methods[] = $m;
        }

        $o = [];
        $o[] = "/* ── Struct: {$cn} ──────────────────────────── */";
        $o[] = 'typedef struct {';
        $o[] = $this->ind('t_object _base;');
        $o[] = "} {$cn};";
        $o[] = '';
        $o[] = "void {$cn}___construct({$cn}* self, t_int argc, t_array* argv);";
        $o[] = "void {$cn}___destruct({$cn}* self);";
        foreach ($methods as $m) {
            $o[] = $this->methodDecl($m) . ';';
        }
        if ($isMain) {
            $o[] = "{$cn}* new_{$cn}(t_int argc, t_array* argv);";
        } else {
            $o[] = "{$cn}* new_{$cn}(void);";
        }
        $o[] = '';

        return implode("\n", $o);
    }

    /** Phase 2: VTable + 方法实现 + allocator */
    private function emitClassImpl(ClassNode $class, bool $isMain): string
    {
        $cn = self::classCName($class);
        $ctor = $dtor = null;
        $methods = [];
        foreach ($class->methods as $m) {
            if ($m->name === '__construct') $ctor = $m;
            elseif ($m->name === '__destruct') $dtor = $m;
            else $methods[] = $m;
        }

        $o = [];

        // VTable
        $o[] = "/* ── VTable: {$cn} ──────────────────────────── */";
        $o[] = "static const ClassVTable _vtable_{$cn} = {";
        $o[] = $this->ind("    .name    = \"{$cn}\",");
        $o[] = $this->ind("    .type_id = 0,");
        $o[] = $this->ind("    .dtor    = (void(*)(void*)){$cn}___destruct,");
        $o[] = $this->ind("};");
        $o[] = '';

        // __construct（固定签名）
        $o[] = "void {$cn}___construct({$cn}* self, t_int argc, t_array* argv) {";
        $o[] = $this->ind('if (self == NULL) return;');
        if ($ctor && !empty($ctor->body)) {
            foreach ($ctor->body as $s) $o[] = $this->ind($s->accept($this));
        } else {
            $o[] = $this->ind('(void)argc;');
            $o[] = $this->ind('(void)argv;');
        }
        $o[] = '}';
        $o[] = '';

        // __destruct（固定签名）
        $o[] = "void {$cn}___destruct({$cn}* self) {";
        $o[] = $this->ind('if (self == NULL) return;');
        if ($dtor && !empty($dtor->body)) {
            foreach ($dtor->body as $s) $o[] = $this->ind($s->accept($this));
        }
        $o[] = '}';
        $o[] = '';

        // 用户方法
        foreach ($methods as $m) {
            $o[] = $m->accept($this);
            $o[] = '';
        }

        // Allocator — Main 有参数，辅助类无参数
        $o[] = "/* ── Allocator: new_{$cn} ──────────────── */";
        if ($isMain) {
            $o[] = "{$cn}* new_{$cn}(t_int argc, t_array* argv) {";
        } else {
            $o[] = "{$cn}* new_{$cn}(void) {";
        }
        $o[] = $this->ind("{$cn}* self = ({$cn}*)calloc(1, sizeof({$cn}));");
        $o[] = $this->ind('if (self == NULL) return NULL;');
        $o[] = $this->ind("self->_base.vtable   = &_vtable_{$cn};");
        $o[] = $this->ind("self->_base.refcount = 1;");
        if ($isMain) {
            $o[] = $this->ind("{$cn}___construct(self, argc, argv);");
        } else {
            $o[] = $this->ind("t_int _dummy_argc = 0; t_array* _dummy_argv = NULL;");
            $o[] = $this->ind("{$cn}___construct(self, _dummy_argc, _dummy_argv);");
        }
        $o[] = $this->ind('return self;');
        $o[] = '}';
        $o[] = '';

        return implode("\n", $o);
    }

    // ============================================================
    public function visitClass(ClassNode $node): string { return ''; }

    public function visitFunction(FunctionNode $node): string
    {
        $this->declaredVars = [];
        $this->scopeObjects = [];
        $ret = self::mapType($node->returnType);
        $params = array_map(fn($p) => $this->visitParam($p), $node->params);
        // 参数也标记为已声明
        foreach ($node->params as $p) {
            $this->declaredVars[self::varName($p->name)] = true;
        }
        $lines = [];
        $lines[] = 'static ' . $ret . ' tphp_' . self::funcCName($node) . '(' . implode(', ', $params) . ') {';
        foreach ($node->body as $s) $lines[] = $this->ind($s->accept($this));
        // 自动析构本作用域内的对象变量
        foreach ($this->scopeObjects as $ov) {
            $lines[] = $this->ind("tphp_object_free(&{$ov}->_base);");
        }
        $lines[] = '}';
        return implode("\n", $lines);
    }

    public function visitMethod(MethodNode $node): string
    {
        $this->declaredVars = [];
        $this->scopeObjects = [];
        // self + params are all declared
        $this->declaredVars['self'] = true;
        foreach ($node->params as $p) {
            $this->declaredVars[self::varName($p->name)] = true;
        }
        $lines = [];
        $lines[] = $this->methodImpl($node) . ' {';
        $lines[] = $this->ind('if (self == NULL) return;');
        if (empty($node->body)) {
            foreach ($node->params as $p) $lines[] = $this->ind("(void)" . self::varName($p->name) . ";");
        } else {
            foreach ($node->body as $s) $lines[] = $this->ind($s->accept($this));
        }
        // 自动析构本作用域内的对象变量
        foreach ($this->scopeObjects as $ov) {
            $lines[] = $this->ind("tphp_object_free(&{$ov}->_base);");
        }
        $lines[] = '}';
        return implode("\n", $lines);
    }

    public function visitParam(ParamNode $node): string
    {
        return self::mapType($node->type) . ' ' . self::varName($node->name);
    }

    // ============================================================
    public function visitEchoStmt(EchoStmtNode $node): string
    {
        $parts = [];
        foreach ($node->exprs as $e) {
            $code = $e->accept($this);
            // 如果表达式不是字符串字面量/变量引用，可能需要转换
            if ($e instanceof StringLiteralExpr) {
                $parts[] = "tphp_echo({$code});";
            } elseif ($e instanceof VariableExpr) {
                // 变量：推导类型决定是否需要转换
                $vn = self::varName($e->name);
                $vt = $this->varTypes[$vn] ?? '';
                if ($vt === 't_string' || $vt === 't_int' || $vt === 't_float' || $vt === 't_bool') {
                    $parts[] = $this->echoWrap($vt, $code);
                } else {
                    $parts[] = "tphp_echo({$code});";
                }
            } elseif ($e instanceof CallExpr) {
                // 函数调用：默认当作 echo 的参数，推导返回类型
                $parts[] = $this->echoWrap('t_int', $code); // 默认 int
            } else {
                $parts[] = "tphp_echo({$code});";
            }
        }
        return implode("\n" . $this->indentStr(), $parts);
    }

    private function echoWrap(string $type, string $code): string
    {
        return match ($type) {
            't_string' => "tphp_echo({$code});",
            't_int'    => "tphp_echo(tphp_str_from_int({$code}));",
            't_float'  => "tphp_echo(tphp_str_from_float({$code}));",
            't_bool'   => "tphp_echo(tphp_str_from_bool({$code}));",
            default    => "tphp_echo({$code});",
        };
    }

    public function visitReturnStmt(ReturnStmtNode $node): string
    {
        return $node->expr ? 'return ' . $node->expr->accept($this) . ';' : 'return;';
    }

    public function visitAssignStmt(AssignStmtNode $node): string
    {
        $var = self::varName($node->varName);
        $expr = $node->expr->accept($this);
        $isDeclared = isset($this->declaredVars[$var]);
        $this->declaredVars[$var] = true;

        // new ClassName(...) → tphp_ClassName* var = expr; + 记录为对象变量
        if ($node->expr instanceof NewExpr) {
            $cn = self::classRefName($node->expr->className);
            $this->varTypes[$var] = $cn;
            $this->scopeObjects[] = $var;
            return "{$cn}* {$var} = {$expr};";
        }

        // null 赋值 → PHP 类型为 null，C 类型用 void* 占位
        if ($node->expr instanceof NullLiteralExpr) {
            if (!$isDeclared) {
                $this->varTypes[$var] = 'null';
                return "void* {$var} = null;";
            }
            $this->varTypes[$var] = 'null';
            return "{$var} = null;";
        }

        // 首次赋值 → 推导类型并声明
        if (!$isDeclared) {
            $cType = $this->inferType($node->expr);
            $this->varTypes[$var] = $cType;
            return "{$cType} {$var} = {$expr};";
        }

        return "{$var} = {$expr};";
    }

    /** 从 AST 表达式推导 C 类型 */
    private function inferType(ExprNode $expr): string
    {
        $class = get_class($expr);
        if (isset(self::$litTypeMap[$class])) {
            return self::$litTypeMap[$class];
        }
        if ($expr instanceof NullLiteralExpr) {
            return 'null';
        }
        if ($expr instanceof BinaryExpr) {
            return $this->inferType($expr->left); // 取左操作数类型
        }
        if ($expr instanceof ArrayLiteralExpr) {
            return 't_array*';
        }
        if ($expr instanceof ClosureExpr) {
            return 't_callback';
        }
        if ($expr instanceof VariableExpr) {
            $vn = self::varName($expr->name);
            return $this->varTypes[$vn] ?? 't_int';
        }
        if ($expr instanceof CallExpr) {
            return 't_int'; // 默认函数返回 int，后续可优化
        }
        return 't_int'; // fallback
    }

    public function visitExprStmt(ExprStmtNode $node): string
    {
        return $node->expr->accept($this) . ';';
    }

    // ============================================================
    public function visitStringLiteral(StringLiteralExpr $node): string
    {
        $val = str_replace('"', '\\"', $node->value);
        return "STR_LIT(\"{$val}\")";
    }

    public function visitIntLiteral(IntLiteralExpr $node): string    { return (string)$node->value; }
    public function visitFloatLiteral(FloatLiteralExpr $node): string { return (string)$node->value; }
    public function visitBoolLiteral(BoolLiteralExpr $node): string   { return $node->value ? 'true' : 'false'; }
    public function visitNullLiteral(NullLiteralExpr $node): string   { return 'null'; }

    public function visitArrayLiteral(ArrayLiteralExpr $node): string
    {
        // 生成复合语句表达式，创建 t_array* 并填充
        $tmpName = "_arr_" . (++$this->tmpVarCounter);
        return "({ " . $this->genArrayLiteralInline($node, $tmpName) . " " . $tmpName . "; })";
    }

    /** 生成数组字面量的声明+填充代码（不含外层 ({})） */
    private function genArrayLiteralInline(ArrayLiteralExpr $node, string $varName): string
    {
        $parts = [];
        $parts[] = "t_array* {$varName} = tphp_arr_create();";
        $parts[] = "if ({$varName} != NULL) {";
        foreach ($node->elements as $el) {
            $code = $el->accept($this);
            // 根据元素类型包装为 t_var
            if ($el instanceof StringLiteralExpr) {
                $parts[] = "tphp_arr_push({$varName}, VAR_STRING({$code}));";
            } elseif ($el instanceof IntLiteralExpr) {
                $parts[] = "tphp_arr_push({$varName}, VAR_INT({$code}));";
            } elseif ($el instanceof FloatLiteralExpr) {
                $parts[] = "tphp_arr_push({$varName}, VAR_FLOAT({$code}));";
            } elseif ($el instanceof BoolLiteralExpr) {
                $parts[] = "tphp_arr_push({$varName}, VAR_BOOL({$code}));";
            } elseif ($el instanceof NullLiteralExpr) {
                $parts[] = "tphp_arr_push({$varName}, VAR_NULL());";
            } elseif ($el instanceof ArrayLiteralExpr) {
                // 嵌套数组
                $subCode = $el->accept($this);
                $parts[] = "tphp_arr_push({$varName}, VAR_ARRAY({$subCode}));";
            } elseif ($el instanceof ClosureExpr) {
                // 闭包作为数组元素
                $subCode = $el->accept($this);
                $parts[] = "tphp_arr_push({$varName}, VAR_CALLBACK({$subCode}));";
            } elseif ($el instanceof VariableExpr) {
                $vn = self::varName($el->name);
                $vt = $this->varTypes[$vn] ?? 't_int';
                $wrap = match ($vt) {
                    't_int'      => "VAR_INT({$vn})",
                    't_float'    => "VAR_FLOAT({$vn})",
                    't_string'   => "VAR_STRING({$vn})",
                    't_bool'     => "VAR_BOOL({$vn})",
                    't_array*'   => "VAR_ARRAY({$vn})",
                    't_callback' => "VAR_CALLBACK({$vn})",
                    default      => "VAR_NULL()",
                };
                $parts[] = "tphp_arr_push({$varName}, {$wrap});";
            } else {
                // BinaryExpr, CallExpr 等 —— 默认 int 类型
                $parts[] = "tphp_arr_push({$varName}, VAR_INT({$code}));";
            }
        }
        $parts[] = '}';
        return implode(' ', $parts);
    }

    public function visitClosure(ClosureExpr $node): string
    {
        $id = ++$this->closureCounter;
        $name = "_closure_{$id}";
        $ret = self::mapType($node->returnType);
        $paramDecls = array_map(fn($p) => $this->visitParam($p), $node->params);
        $paramStr = implode(', ', $paramDecls);

        // 构建闭包函数的 C 实现（文件作用域，不缩进）
        $savedDeclared = $this->declaredVars;
        $savedObjs     = $this->scopeObjects;
        $savedTypes    = $this->varTypes;
        $savedIndent   = $this->indent;

        $this->declaredVars = [];
        $this->scopeObjects = [];
        $this->varTypes     = [];
        $this->indent       = 0;
        foreach ($node->params as $p) {
            $this->declaredVars[self::varName($p->name)] = true;
        }

        $implLines = [];
        $implLines[] = "{$ret} {$name}({$paramStr}) {";
        if (empty($node->body)) {
            foreach ($node->params as $p) {
                $implLines[] = '    (void)' . self::varName($p->name) . ';';
            }
        } else {
            foreach ($node->body as $s) {
                $implLines[] = '    ' . $s->accept($this);
            }
        }
        foreach ($this->scopeObjects as $ov) {
            $implLines[] = '    ' . "tphp_object_free(&{$ov}->_base);";
        }
        $implLines[] = '}';

        $this->closureImpls[] = implode("\n", $implLines);

        // 恢复外层作用域
        $this->declaredVars = $savedDeclared;
        $this->scopeObjects = $savedObjs;
        $this->varTypes     = $savedTypes;
        $this->indent       = $savedIndent;

        // 返回 GNU 复合表达式：非 static 前向声明（块作用域合法）+ t_callback
        return "({ {$ret} {$name}({$paramStr});"
            . " (t_callback){ .func = (void*){$name}, .env = NULL }; })";
    }

    public function visitVariable(VariableExpr $node): string
    {
        $n = self::varName($node->name);
        return $n === '$this' ? 'self' : $n;
    }

    public function visitBinary(BinaryExpr $node): string
    {
        return '(' . $node->left->accept($this) . ' ' . $node->operator . ' ' . $node->right->accept($this) . ')';
    }

    public function visitCall(CallExpr $node): string
    {
        // var_dump 内置函数 —— 包装参数为 t_var 并调用 tphp_var_dump
        if ($node->callee === null && $node->name === 'var_dump') {
            return $this->generateVarDump($node->args);
        }

        // 闭包调用: $h() → ((t_int(*)(...))h.func)(args)
        if ($node->callee !== null && $node->name === '__invoke') {
            return $this->generateClosureCall($node->callee, $node->args);
        }

        $args = array_map(fn($a) => $a->accept($this), $node->args);
        if ($node->callee === null) {
            // 独立函数加 tphp_ 前缀，命名空间名已 mangled
            return 'tphp_' . self::mangleCName($node->name) . '(' . implode(', ', $args) . ')';
        }
        $callee = $node->callee->accept($this);
        // 方法调用：self 作为第一个参数
        $allArgs = array_merge([$callee], $args);
        // 类名推导（self 用 className，其他从 varTypes 查）
        if ($callee === 'self') {
            $cn = $this->className;
        } else {
            $raw = $this->varTypes[$callee] ?? $callee;
            // 如果 varTypes 里存的是 PHP 命名空间名（含 \），转 C 名
            $cn = str_contains($raw, '\\') ? self::classRefName($raw) : $raw;
        }
        return "{$cn}_{$node->name}(" . implode(', ', $allArgs) . ')';
    }

    /** 生成 var_dump 调用：将参数包装为 t_var */
    private function generateVarDump(array $args): string
    {
        $wrapped = [];
        foreach ($args as $arg) {
            $wrapped[] = $this->wrapVar($arg);
        }
        return 'tphp_var_dump(' . implode(', ', $wrapped) . ')';
    }

    /** 生成闭包调用: ((t_int(*)(t_int,...))var.func)(args) */
    private function generateClosureCall(ExprNode $callee, array $args): string
    {
        $calleeCode = $callee->accept($this);
        $argCodes = array_map(fn($a) => $a->accept($this), $args);
        $argStr = implode(', ', $argCodes);
        $nargs = count($args);

        if ($nargs === 0) {
            return "((t_int(*)(void)){$calleeCode}.func)()";
        }
        $paramTypes = implode(', ', array_fill(0, $nargs, 't_int'));
        return "((t_int(*)({$paramTypes})){$calleeCode}.func)({$argStr})";
    }

    /** 将表达式包装为 t_var */
    private function wrapVar(ExprNode $expr): string
    {
        if ($expr instanceof StringLiteralExpr) {
            return 'VAR_STRING(' . $expr->accept($this) . ')';
        }
        if ($expr instanceof IntLiteralExpr) {
            return 'VAR_INT(' . $expr->accept($this) . ')';
        }
        if ($expr instanceof FloatLiteralExpr) {
            return 'VAR_FLOAT(' . $expr->accept($this) . ')';
        }
        if ($expr instanceof BoolLiteralExpr) {
            return 'VAR_BOOL(' . $expr->accept($this) . ')';
        }
        if ($expr instanceof NullLiteralExpr) {
            return 'VAR_NULL()';
        }
        if ($expr instanceof VariableExpr) {
            $vn = self::varName($expr->name);
            $vt = $this->varTypes[$vn] ?? 't_int';
            return match ($vt) {
                't_int'      => "VAR_INT({$vn})",
                't_float'    => "VAR_FLOAT({$vn})",
                't_string'   => "VAR_STRING({$vn})",
                't_bool'     => "VAR_BOOL({$vn})",
                't_array*'   => "VAR_ARRAY({$vn})",
                't_callback' => "VAR_CALLBACK({$vn})",
                'null'       => "VAR_NULL()",
                default      => "VAR_NULL()",
            };
        }
        if ($expr instanceof ArrayLiteralExpr) {
            // GNU 复合表达式: VAR_ARRAY(({ t_array* _a = ...; ...; _a; }))
            $tmpName = "_vd_arr_" . (++$this->tmpVarCounter);
            $arrCode = $this->genArrayLiteralInline($expr, $tmpName);
            return "VAR_ARRAY(({ {$arrCode} {$tmpName}; }))";
        }
        // 默认 int
        $code = $expr->accept($this);
        return "VAR_INT({$code})";
    }

    public function visitCast(CastExpr $node): string
    {
        return '((' . self::mapType($node->castType) . ')(' . $node->expr->accept($this) . '))';
    }

    public function visitNew(NewExpr $node): string
    {
        $cn = self::classRefName($node->className);
        $args = array_map(fn($a) => $a->accept($this), $node->args);
        if (empty($args) && $cn !== $this->className) {
            return "new_{$cn}()";
        }
        return "new_{$cn}(" . implode(', ', $args) . ')';
    }

    // ============================================================
    private function generateCEntry(): string
    {
        return implode("\n", [
            "/* ── C entry: main() ─────────────────────────── */",
            "int main(int argc, char* argv[]) {",
            $this->ind("t_array* _argv = tphp_build_argv(argc, argv);"),
            $this->ind("{$this->className}* _main = new_{$this->className}((t_int)argc, _argv);"),
            $this->ind("if (_main == NULL) { tphp_arr_free(_argv); return 1; }"),
            $this->ind("{$this->className}_main(_main);"),
            $this->ind("tphp_object_free(&_main->_base);"),
            $this->ind("tphp_arr_free(_argv);"),
            $this->ind("return 0;"),
            "}",
        ]);
    }

    // ============================================================
    private function methodDecl(MethodNode $m): string
    {
        $ret = self::mapType($m->returnType);
        $params = array_map(fn($p) => $this->visitParam($p), $m->params);
        return "{$ret} {$this->className}_{$m->name}({$this->className}* self" .
            (empty($params) ? '' : ', ' . implode(', ', $params)) . ')';
    }

    private function methodImpl(MethodNode $m): string { return $this->methodDecl($m); }

    public static function mapType(string $t): string { return self::$typeMap[$t] ?? "{$t}*"; }
    public static function varName(string $v): string { return $v === '$this' ? 'self' : ltrim($v, '$'); }

    /** 将 PHP 命名空间名转为 C 标识符: Demo\Foo → Demo_Foo */
    public static function mangleCName(string $name): string {
        return str_replace('\\', '_', $name);
    }

    /** 从类节点获取 C 标识符: tphp_namespace_Name */
    private static function classCName(ClassNode $class): string {
        $base = ($class->namespace !== '')
            ? self::mangleCName($class->namespace) . '_' . $class->name
            : $class->name;
        return 'tphp_' . $base;
    }

    /** 从已解析类名生成 C 引用名（visitNew/Call 等非 ClassNode 上下文中使用） */
    private static function classRefName(string $resolvedName): string {
        return 'tphp_' . self::mangleCName($resolvedName);
    }

    /** 从函数节点获取 C 标识符: namespace_name */
    private static function funcCName(FunctionNode $fn): string {
        return ($fn->namespace !== '')
            ? self::mangleCName($fn->namespace) . '_' . $fn->name
            : $fn->name;
    }

    private function indentStr(): string { return str_repeat('    ', $this->indent); }
    private function ind(string $l): string { return $this->indentStr() . $l; }
}
