<?php

declare(strict_types=1);

// ============================================================
// FlatCodeGenerator — 消费 FlatAst 生成 C 代码
//
// 设计目标：
//   - 不修改现有 src/CodeGenerator.php（仍服务于主编译流水线）
//   - 专门消费 FlatAst 数据结构（已被 FlatTypeChecker 标注 typ 字段）
//   - 输出结构正确、可读的 C 代码字符串
//
// 核心入口：
//   - generate(): string        — 生成完整 C 代码
//   - genNode(int $idx): string — dispatch by kind 生成单节点代码
//   - genExpr(int $idx): string — 表达式代码生成
//   - genStmt(int $idx): string — 语句代码生成（带缩进）
//
// 类型映射：
//   - 节点 typ 字段（Type::idx()）→ C 类型字符串
//   - 函数/参数声明 returnType/type（PHP 类型字符串）→ C 类型字符串
// ============================================================

class FlatCodeGenerator
{
    private FlatAst $ast;

    /** 当前缩进层级（每个层级 4 空格） */
    private int $indent = 0;

    /** 收集的顶层函数 C 代码（每个元素是一个完整 C 函数字符串） */
    private array $functions = [];

    /** main() 函数体语句列表 */
    private array $mainBody = [];

    /** 已生成的字符串字面量计数（用于唯一命名） */
    private int $strLitCounter = 0;

    public function __construct(FlatAst $ast)
    {
        $this->ast = $ast;
    }

    // ─────────────────────────────────────────────────────────────
    // 公共入口
    // ─────────────────────────────────────────────────────────────

    /**
     * 生成完整 C 代码：辅助函数声明 + 用户函数 + main()。
     */
    public function generate(): string
    {
        $this->functions = [];
        $this->mainBody  = [];

        if ($this->ast->root < 0) {
            return "/* empty program */\n";
        }

        // 生成所有顶层节点：函数定义 → 入 main()
        $this->genProgram($this->ast->root);

        // 拼装最终 C 代码
        $out = "// Generated by FlatCodeGenerator\n";
        $out .= "#include <stdio.h>\n";
        $out .= "#include \"tphp_runtime.h\"\n\n";

        // 用户函数
        foreach ($this->functions as $fn) {
            $out .= $fn . "\n\n";
        }

        // main()
        $out .= "int main(int argc, char** argv) {\n";
        foreach ($this->mainBody as $stmt) {
            $out .= $stmt . "\n";
        }
        $out .= "    return 0;\n";
        $out .= "}\n";

        return $out;
    }

    // ─────────────────────────────────────────────────────────────
    // genNode：按 NodeKind 分发
    // ─────────────────────────────────────────────────────────────

    /**
     * 生成单个节点的代码（dispatch by kind）。
     * 对于语句节点返回带缩进的代码行；对于表达式节点返回表达式字符串。
     */
    public function genNode(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        return match ($node['kind']) {
            // === 顶层结构 ===
            NodeKind::ProgramNode      => $this->genProgram($idx),
            NodeKind::FunctionNode     => $this->genFunction($idx),

            // === 语句 ===
            NodeKind::EchoStmtNode           => $this->genEcho($idx),
            NodeKind::ReturnStmtNode         => $this->genReturn($idx),
            NodeKind::AssignStmtNode         => $this->genAssign($idx),
            NodeKind::IfStmtNode             => $this->genIf($idx),
            NodeKind::WhileStmtNode          => $this->genWhile($idx),
            NodeKind::ForStmtNode            => $this->genFor($idx),
            NodeKind::ExprStmtNode           => $this->genExprStmt($idx),
            NodeKind::BlockStmtNode          => $this->genBlock($idx),
            NodeKind::BreakStmtNode          => $this->indentStr() . 'break;',
            NodeKind::ContinueStmtNode       => $this->indentStr() . 'continue;',
            NodeKind::NopStmtNode            => $this->indentStr() . '/* nop */',

            // === 表达式 ===
            NodeKind::IntLiteralExpr,
            NodeKind::StringLiteralExpr,
            NodeKind::FloatLiteralExpr,
            NodeKind::BoolLiteralExpr,
            NodeKind::NullLiteralExpr,
            NodeKind::VariableExpr,
            NodeKind::BinaryExpr,
            NodeKind::UnaryExpr,
            NodeKind::PostfixExpr,
            NodeKind::CompoundAssignExpr,
            NodeKind::TernaryExpr,
            NodeKind::NullCoalesceExpr,
            NodeKind::CallExpr,
            NodeKind::CastExpr,
            NodeKind::ArrayAccessExpr,
            NodeKind::PropertyAccessExpr,
            NodeKind::ArrayLiteralExpr       => $this->genExpr($idx),

            default => '/* unhandled kind: ' . $node['kind']->name . ' */',
        };
    }

    // ─────────────────────────────────────────────────────────────
    // genExpr：表达式代码生成
    // ─────────────────────────────────────────────────────────────

    /**
     * 生成表达式代码（返回表达式字符串，不带末尾分号）。
     */
    public function genExpr(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        return match ($node['kind']) {
            NodeKind::IntLiteralExpr      => $this->genIntLiteral($idx),
            NodeKind::StringLiteralExpr   => $this->genStringLiteral($idx),
            NodeKind::FloatLiteralExpr    => $this->genFloatLiteral($idx),
            NodeKind::BoolLiteralExpr     => $this->genBoolLiteral($idx),
            NodeKind::NullLiteralExpr     => '0',
            NodeKind::VariableExpr        => $this->genVariable($idx),
            NodeKind::BinaryExpr          => $this->genBinary($idx),
            NodeKind::UnaryExpr           => $this->genUnary($idx),
            NodeKind::PostfixExpr         => $this->genPostfix($idx),
            NodeKind::CompoundAssignExpr  => $this->genCompoundAssign($idx),
            NodeKind::TernaryExpr         => $this->genTernary($idx),
            NodeKind::NullCoalesceExpr    => $this->genNullCoalesce($idx),
            NodeKind::CallExpr            => $this->genCall($idx),
            NodeKind::CastExpr            => $this->genCast($idx),
            NodeKind::ArrayAccessExpr     => $this->genArrayAccess($idx),
            NodeKind::PropertyAccessExpr  => $this->genPropertyAccess($idx),
            NodeKind::ArrayLiteralExpr    => $this->genArrayLiteral($idx),
            default                       => '/* unhandled expr: ' . $node['kind']->name . ' */',
        };
    }

    // ─────────────────────────────────────────────────────────────
    // genStmt：语句代码生成（返回带缩进的代码行）
    // ─────────────────────────────────────────────────────────────

    /**
     * 生成语句代码（返回带缩进的字符串，可能多行）。
     */
    public function genStmt(int $idx): string
    {
        return $this->genNode($idx);
    }

    // ═══════════════════════════════════════════════════════════════
    // 顶层结构
    // ═══════════════════════════════════════════════════════════════

    /**
     * 生成 ProgramNode：函数定义生成独立 C 函数，顶层语句归入 main()。
     *
     * Children 顺序（FlatAstConverter.visitProgram）：
     *   mainClass → extraClasses → functions → constants → enums
     */
    private function genProgram(int $idx): string
    {
        $extra = $this->ast->nodes[$idx]['extra'];
        $offset = 0;

        $hasMainClass = $extra['hasMainClass'] ?? false;
        if ($hasMainClass) {
            $offset++;  // mainClass 暂不展开（仅类方法/属性）
        }
        $extraClassCount = $extra['extraClassCount'] ?? 0;
        $offset += $extraClassCount;

        $functionCount = $extra['functionCount'] ?? 0;
        for ($i = 0; $i < $functionCount; $i++) {
            $fnIdx = $this->ast->child($idx, $offset + $i);
            // 生成函数定义并追加到 $this->functions
            $fnCode = $this->genFunction($fnIdx);
            $this->functions[] = $fnCode;
        }
        return '';
    }

    /**
     * 生成 FunctionNode 的 C 函数定义。
     *   PHP: function add(int $a, int $b): int { return $a + $b; }
     *   C:   t_int tphp_fn_add(t_int a, t_int b) { return (a + b); }
     *
     * Children 顺序：attributes → params → body
     */
    private function genFunction(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $extra = $node['extra'];
        $name = (string)($node['value'] ?? 'anon');
        $retType = $this->phpTypeToCType($extra['returnType'] ?? '');

        $attributeCount = $extra['attributeCount'] ?? 0;
        $paramCount     = $extra['paramCount'] ?? 0;

        // 参数列表
        $params = [];
        for ($i = 0; $i < $paramCount; $i++) {
            $pIdx = $this->ast->child($idx, $attributeCount + $i);
            $params[] = $this->genParam($pIdx);
        }
        $paramStr = implode(', ', $params);
        if ($paramStr === '') $paramStr = 'void';

        // 函数体
        $bodyStart = $attributeCount + $paramCount;
        $bodyEnd   = $this->ast->childCount($idx);

        $savedIndent = $this->indent;
        $this->indent = 1;
        $bodyLines = [];
        for ($i = $bodyStart; $i < $bodyEnd; $i++) {
            $stmtIdx = $this->ast->child($idx, $i);
            $line = $this->genStmt($stmtIdx);
            if ($line !== '') $bodyLines[] = $line;
        }
        $this->indent = $savedIndent;

        $cName = 'tphp_fn_' . $name;
        $body = implode("\n", $bodyLines);
        if ($body === '') $body = $this->indentStr() . '/* empty body */';

        return "{$retType} {$cName}({$paramStr}) {\n{$body}\n}";
    }

    /**
     * 生成参数声明：PHP `int $a` → C `t_int a`。
     */
    private function genParam(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $extra = $node['extra'];
        $name = ltrim((string)($node['value'] ?? ''), '$');
        $type = $this->phpTypeToCType($extra['type'] ?? '');
        return "{$type} {$name}";
    }

    // ═══════════════════════════════════════════════════════════════
    // 字面量
    // ═══════════════════════════════════════════════════════════════

    private function genIntLiteral(int $idx): string
    {
        $v = $this->ast->nodes[$idx]['value'];
        return (string)(int)$v;
    }

    private function genFloatLiteral(int $idx): string
    {
        $v = $this->ast->nodes[$idx]['value'];
        $s = (string)(float)$v;
        // 确保 C 浮点字面量带小数点
        if (!str_contains($s, '.') && !str_contains($s, 'e') && !str_contains($s, 'E')) {
            $s .= '.0';
        }
        return $s;
    }

    private function genBoolLiteral(int $idx): string
    {
        $v = $this->ast->nodes[$idx]['value'];
        return $v ? '1' : '0';
    }

    private function genStringLiteral(int $idx): string
    {
        // Lexer 保留 PHP 源码中的转义序列（如 \" \n \t \r \\），未做反解析。
        // 这里逐字符扫描，按 C 字符串字面量规则重新转义：
        //   - 已有 \X 转义序列：保留原样（\" \n \t \r \\ 等已是合法 C 转义）
        //   - 原始控制字符（LF/CR/TAB）：转为 \n \r \t
        //   - 原始双引号 "：转为 \"
        //   - 原始反斜杠 \ 不构成合法转义序列时：转为 \\
        $v = (string)($this->ast->nodes[$idx]['value'] ?? '');
        $result = '';
        $len = strlen($v);
        for ($i = 0; $i < $len; $i++) {
            $ch = $v[$i];
            if ($ch === '\\' && $i + 1 < $len) {
                $next = $v[$i + 1];
                if (strpos('"\\ntrabefvx?\'01234567', $next) !== false) {
                    $result .= '\\' . $next;
                } else {
                    $result .= '\\\\' . $next;
                }
                $i++;
            } elseif ($ch === '\\') {
                $result .= '\\\\';
            } elseif ($ch === '"') {
                $result .= '\\"';
            } elseif ($ch === "\n") {
                $result .= '\\n';
            } elseif ($ch === "\r") {
                $result .= '\\r';
            } elseif ($ch === "\t") {
                $result .= '\\t';
            } else {
                $result .= $ch;
            }
        }
        return '"' . $result . '"';
    }

    // ═══════════════════════════════════════════════════════════════
    // 变量与运算
    // ═══════════════════════════════════════════════════════════════

    /**
     * 变量引用：PHP `$a` → C `a`。
     */
    private function genVariable(int $idx): string
    {
        $name = (string)($this->ast->nodes[$idx]['value'] ?? '');
        return ltrim($name, '$');
    }

    /**
     * 二元运算：根据操作符生成不同形式。
     *   +  → (left + right)
     *   .  → tphp_str_concat(left, right)   字符串连接
     *   == / != / < / > 等 → (left OP right)
     *   && / || → (left && right)
     */
    private function genBinary(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $op = (string)($node['value'] ?? '');

        $leftIdx  = $this->ast->child($idx, 0);
        $rightIdx = $this->ast->child($idx, 1);
        $left  = $this->genExpr($leftIdx);
        $right = $this->genExpr($rightIdx);

        // PHP 字符串连接 → C 函数调用
        if ($op === '.') {
            return "tphp_str_concat({$left}, {$right})";
        }
        if ($op === '===') return "({$left} == {$right})";
        if ($op === '!==') return "({$left} != {$right})";
        if ($op === '<=>') return "tphp_spaceship({$left}, {$right})";
        if ($op === '**')  return "tphp_pow({$left}, {$right})";

        // 算术、比较、位、逻辑运算：直接映射到 C 运算符
        return "({$left} {$op} {$right})";
    }

    /**
     * 一元运算：-x / !x / ~x → (-x) / (!x) / (~x)
     */
    private function genUnary(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $op = (string)($node['value'] ?? '');
        $operandIdx = $this->ast->child($idx, 0);
        $operand = $this->genExpr($operandIdx);
        return "({$op}{$operand})";
    }

    /**
     * 后置自增/自减：$x++ / $x-- → (x++) / (x--)
     */
    private function genPostfix(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $op = (string)($node['value'] ?? '');
        $operandIdx = $this->ast->child($idx, 0);
        $operand = $this->genExpr($operandIdx);
        return "({$operand}{$op})";
    }

    /**
     * 复合赋值表达式：$x += $y → (x += y)（作为表达式）
     */
    private function genCompoundAssign(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $op = (string)($node['value'] ?? '');
        $leftIdx  = $this->ast->child($idx, 0);
        $rightIdx = $this->ast->child($idx, 1);
        $left  = $this->genExpr($leftIdx);
        $right = $this->genExpr($rightIdx);

        // .= → tphp_str_concat 赋值（简化为函数）
        if ($op === '.=') {
            return "({$left} = tphp_str_concat({$left}, {$right}))";
        }
        return "({$left} {$op} {$right})";
    }

    /**
     * 三元：cond ? then : else → (cond ? then : else)
     */
    private function genTernary(int $idx): string
    {
        $condIdx = $this->ast->child($idx, 0);
        $thenIdx = $this->ast->child($idx, 1);
        $elseIdx = $this->ast->child($idx, 2);
        $cond = $this->genExpr($condIdx);
        $then = $this->genExpr($thenIdx);
        $else = $this->genExpr($elseIdx);
        return "({$cond} ? {$then} : {$else})";
    }

    /**
     * ?? 运算：left ?? right → tphp_null_coalesce(left, right)
     */
    private function genNullCoalesce(int $idx): string
    {
        $leftIdx  = $this->ast->child($idx, 0);
        $rightIdx = $this->ast->child($idx, 1);
        $left  = $this->genExpr($leftIdx);
        $right = $this->genExpr($rightIdx);
        return "tphp_null_coalesce({$left}, {$right})";
    }

    /**
     * 类型转换：(int)x / (string)x → (t_int)x / tphp_to_string(x)
     */
    private function genCast(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $castType = (string)($node['value'] ?? '');
        $operandIdx = $this->ast->child($idx, 0);
        $operand = $this->genExpr($operandIdx);

        $cType = $this->phpTypeToCType($castType);
        if ($castType === 'string') {
            return "tphp_to_string({$operand})";
        }
        if ($castType === 'int' || $castType === 'integer') {
            return "((t_int){$operand})";
        }
        if ($castType === 'float' || $castType === 'double') {
            return "((t_float){$operand})";
        }
        if ($castType === 'bool' || $castType === 'boolean') {
            return "((t_bool){$operand})";
        }
        return "(({$cType}){$operand})";
    }

    /**
     * 数组访问：arr[idx] → arr[idx]
     */
    private function genArrayAccess(int $idx): string
    {
        $arrIdx   = $this->ast->child($idx, 0);
        $indexIdx = $this->ast->child($idx, 1);
        $arr   = $this->genExpr($arrIdx);
        $index = $this->genExpr($indexIdx);
        return "{$arr}[{$index}]";
    }

    /**
     * 属性访问：obj->prop → obj->field
     */
    private function genPropertyAccess(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $prop = (string)($node['value'] ?? '');
        $objIdx = $this->ast->child($idx, 0);
        $obj = $this->genExpr($objIdx);
        return "{$obj}->{$prop}";
    }

    /**
     * 数组字面量：[1, 2, 3] → tphp_arr_lit(3, 1, 2, 3)（简化形式）
     */
    private function genArrayLiteral(int $idx): string
    {
        $children = $this->ast->children($idx);
        $parts = [];
        foreach ($children as $childIdx) {
            // ArrayEntryNode 子节点：[key?, value]
            $entryNode = $this->ast->nodes[$childIdx];
            if ($entryNode['kind'] === NodeKind::ArrayEntryNode) {
                $entryChildren = $this->ast->children($childIdx);
                // value 是最后一个子节点
                $valueIdx = end($entryChildren);
                $parts[] = $this->genExpr($valueIdx);
            } else {
                $parts[] = $this->genExpr($childIdx);
            }
        }
        $count = count($parts);
        $args = implode(', ', $parts);
        return "tphp_arr_lit({$count}{$args})";
    }

    /**
     * 函数调用：add(1, 2) → tphp_fn_add(1, 2)。
     *
     * Children 顺序（FlatAstConverter.visitCall）：
     *   [callee?, arg1, arg2, ...]
     * extra.hasCallee=true 时第一个子节点是 callee（如 $obj->method()）。
     */
    private function genCall(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $extra = $node['extra'];
        $name = (string)($node['value'] ?? '');

        $hasCallee = $extra['hasCallee'] ?? false;
        $isRawC    = $extra['isRawC'] ?? false;

        $argStart = $hasCallee ? 1 : 0;
        $childCount = $this->ast->childCount($idx);

        $args = [];
        for ($i = $argStart; $i < $childCount; $i++) {
            $args[] = $this->genExpr($this->ast->child($idx, $i));
        }
        $argStr = implode(', ', $args);

        // 方法调用：$obj->method(args) → tphp_class_X_method_method(obj, args)
        if ($hasCallee) {
            $calleeIdx = $this->ast->child($idx, 0);
            $calleeCode = $this->genExpr($calleeIdx);
            if ($argStr === '') {
                return "{$name}({$calleeCode})";
            }
            return "{$name}({$calleeCode}, {$argStr})";
        }

        // 全局函数：PHP 函数名 → tphp_fn_<name>
        $cName = $isRawC ? $name : ('tphp_fn_' . $name);
        return "{$cName}({$argStr})";
    }

    // ═══════════════════════════════════════════════════════════════
    // 语句
    // ═══════════════════════════════════════════════════════════════

    /**
     * Echo 语句：echo $x; → tphp_fn_echo(x);
     * 多个参数分别生成多条 echo 调用。
     */
    private function genEcho(int $idx): string
    {
        $children = $this->ast->children($idx);
        $lines = [];
        foreach ($children as $childIdx) {
            $expr = $this->genExpr($childIdx);
            // 根据表达式类型选择转换（简化：直接调用 tphp_fn_echo）
            $lines[] = $this->indentStr() . "tphp_fn_echo({$expr});";
        }
        return implode("\n", $lines);
    }

    /**
     * 赋值语句：$a = expr; → type a = expr;
     * 若 extra.type 为空（无类型注解），则不写类型（假定已声明）。
     */
    private function genAssign(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        $extra = $node['extra'];
        $varName = ltrim((string)($node['value'] ?? ''), '$');
        $typeStr = $extra['type'] ?? '';
        $exprIdx = $this->ast->child($idx, 0);
        $expr = $this->genExpr($exprIdx);

        if ($typeStr !== '') {
            $cType = $this->phpTypeToCType($typeStr);
            return $this->indentStr() . "{$cType} {$varName} = {$expr};";
        }
        return $this->indentStr() . "{$varName} = {$expr};";
    }

    /**
     * Return 语句：return expr; / return;
     */
    private function genReturn(int $idx): string
    {
        $extra = $this->ast->nodes[$idx]['extra'];
        $hasExpr = $extra['hasExpr'] ?? false;
        if (!$hasExpr) {
            return $this->indentStr() . 'return;';
        }
        $exprIdx = $this->ast->child($idx, 0);
        $expr = $this->genExpr($exprIdx);
        return $this->indentStr() . "return {$expr};";
    }

    /**
     * If 语句：
     *   if (cond) { ... } else if (cond2) { ... } else { ... }
     *
     * Children 顺序：cond → thenBody... → elseif... → elseBody...
     * extra: thenBodyCount, elseifCount, elseBodyCount
     */
    private function genIf(int $idx): string
    {
        $extra = $this->ast->nodes[$idx]['extra'];
        $thenBodyCount = $extra['thenBodyCount'] ?? 0;
        $elseifCount   = $extra['elseifCount']   ?? 0;
        $elseBodyCount = $extra['elseBodyCount'] ?? 0;

        $condIdx = $this->ast->child($idx, 0);
        $cond = $this->genExpr($condIdx);

        $offset = 1;

        // then body
        $thenLines = [];
        $savedIndent = $this->indent;
        $this->indent = $savedIndent + 1;
        for ($i = 0; $i < $thenBodyCount; $i++) {
            $line = $this->genStmt($this->ast->child($idx, $offset + $i));
            if ($line !== '') $thenLines[] = $line;
        }
        $offset += $thenBodyCount;
        $this->indent = $savedIndent;

        $out = $this->indentStr() . "if ({$cond}) {\n";
        $out .= implode("\n", $thenLines) . "\n";
        $out .= $this->indentStr() . "}";

        // elseif 分支
        for ($i = 0; $i < $elseifCount; $i++) {
            $elifIdx = $this->ast->child($idx, $offset + $i);
            $out .= $this->genElseIf($elifIdx, $savedIndent);
        }
        $offset += $elseifCount;

        // else body
        if ($elseBodyCount > 0) {
            $elseLines = [];
            $this->indent = $savedIndent + 1;
            for ($i = 0; $i < $elseBodyCount; $i++) {
                $line = $this->genStmt($this->ast->child($idx, $offset + $i));
                if ($line !== '') $elseLines[] = $line;
            }
            $this->indent = $savedIndent;
            $out .= " else {\n";
            $out .= implode("\n", $elseLines) . "\n";
            $out .= $this->indentStr() . "}";
        }

        return $out;
    }

    /**
     * 生成 elseif 分支：} else if (cond) { body }
     * Children: cond → body...
     */
    private function genElseIf(int $idx, int $baseIndent): string
    {
        $extra = $this->ast->nodes[$idx]['extra'];
        $bodyCount = $extra['bodyCount'] ?? 0;
        $condIdx = $this->ast->child($idx, 0);
        $cond = $this->genExpr($condIdx);

        $bodyLines = [];
        $savedIndent = $this->indent;
        $this->indent = $baseIndent + 1;
        for ($i = 0; $i < $bodyCount; $i++) {
            $line = $this->genStmt($this->ast->child($idx, 1 + $i));
            if ($line !== '') $bodyLines[] = $line;
        }
        $this->indent = $baseIndent;

        $out = " else if ({$cond}) {\n";
        $out .= implode("\n", $bodyLines) . "\n";
        $out .= $this->indentStr() . "}";
        return $out;
    }

    /**
     * While 循环：while (cond) { body }
     * Children: cond → body...
     */
    private function genWhile(int $idx): string
    {
        $extra = $this->ast->nodes[$idx]['extra'];
        $bodyCount = $extra['bodyCount'] ?? 0;
        $condIdx = $this->ast->child($idx, 0);
        $cond = $this->genExpr($condIdx);

        $savedIndent = $this->indent;
        $this->indent = $savedIndent + 1;
        $bodyLines = [];
        for ($i = 0; $i < $bodyCount; $i++) {
            $line = $this->genStmt($this->ast->child($idx, 1 + $i));
            if ($line !== '') $bodyLines[] = $line;
        }
        $this->indent = $savedIndent;

        $out = $this->indentStr() . "while ({$cond}) {\n";
        $out .= implode("\n", $bodyLines) . "\n";
        $out .= $this->indentStr() . "}";
        return $out;
    }

    /**
     * For 循环：for (init; cond; step) { body }
     * Children: init?, cond?, step?, body...（可选子节点按 extra.hasInit/hasCondition/hasStep）
     */
    private function genFor(int $idx): string
    {
        $extra = $this->ast->nodes[$idx]['extra'];
        $hasInit      = $extra['hasInit']      ?? false;
        $hasCondition = $extra['hasCondition'] ?? false;
        $hasStep      = $extra['hasStep']      ?? false;
        $bodyCount    = $extra['bodyCount']   ?? 0;

        $offset = 0;
        $init = '';
        $cond = '';
        $step = '';
        if ($hasInit) {
            // init 子节点是表达式或赋值（BinaryExpr with op='='）
            $initIdx = $this->ast->child($idx, $offset);
            $init = $this->genForInit($initIdx);
            $offset++;
        }
        if ($hasCondition) {
            $condIdx = $this->ast->child($idx, $offset);
            $cond = $this->genExpr($condIdx);
            $offset++;
        }
        if ($hasStep) {
            $stepIdx = $this->ast->child($idx, $offset);
            $step = $this->genForStep($stepIdx);
            $offset++;
        }

        $savedIndent = $this->indent;
        $this->indent = $savedIndent + 1;
        $bodyLines = [];
        for ($i = 0; $i < $bodyCount; $i++) {
            $line = $this->genStmt($this->ast->child($idx, $offset + $i));
            if ($line !== '') $bodyLines[] = $line;
        }
        $this->indent = $savedIndent;

        $out = $this->indentStr() . "for ({$init}; {$cond}; {$step}) {\n";
        $out .= implode("\n", $bodyLines) . "\n";
        $out .= $this->indentStr() . "}";
        return $out;
    }

    /**
     * for 循环 init 部分：可能是 BinaryExpr(=) 或 AssignStmt。
     * 生成 `t_int i = 0` 形式（无分号）。
     */
    private function genForInit(int $idx): string
    {
        $node = $this->ast->nodes[$idx];
        if ($node['kind'] === NodeKind::BinaryExpr && (string)$node['value'] === '=') {
            $leftIdx  = $this->ast->child($idx, 0);
            $rightIdx = $this->ast->child($idx, 1);
            $leftNode = $this->ast->nodes[$leftIdx];
            $varName  = ltrim((string)($leftNode['value'] ?? ''), '$');
            $rhs      = $this->genExpr($rightIdx);
            // 用右侧 typ 字段推断类型（默认 t_int）
            $rhsNode = $this->ast->nodes[$rightIdx];
            $cType = $this->typIdxToCType($rhsNode['typ']);
            return "{$cType} {$varName} = {$rhs}";
        }
        return $this->genExpr($idx);
    }

    /**
     * for 循环 step 部分：可能是 PostfixExpr（i++）或 BinaryExpr（i += 1）。
     */
    private function genForStep(int $idx): string
    {
        return $this->genExpr($idx);
    }

    /**
     * 表达式语句：expr;
     */
    private function genExprStmt(int $idx): string
    {
        $exprIdx = $this->ast->child($idx, 0);
        $expr = $this->genExpr($exprIdx);
        return $this->indentStr() . "{$expr};";
    }

    /**
     * 块语句：{ stmt1 stmt2 ... }
     */
    private function genBlock(int $idx): string
    {
        $children = $this->ast->children($idx);
        $savedIndent = $this->indent;
        $this->indent = $savedIndent + 1;
        $lines = [];
        foreach ($children as $childIdx) {
            $line = $this->genStmt($childIdx);
            if ($line !== '') $lines[] = $line;
        }
        $this->indent = $savedIndent;
        $out = $this->indentStr() . "{\n";
        $out .= implode("\n", $lines) . "\n";
        $out .= $this->indentStr() . "}";
        return $out;
    }

    // ═══════════════════════════════════════════════════════════════
    // 类型映射
    // ═══════════════════════════════════════════════════════════════

    /**
     * PHP 类型字符串 → C 类型字符串
     * 与 FlatTypeChecker::phpTypeToCType 一致。
     */
    private function phpTypeToCType(string $phpType): string
    {
        $phpType = trim($phpType);
        if ($phpType === '' || $phpType === 'mixed') return 't_var';
        if (str_starts_with($phpType, '?')) {
            $phpType = substr($phpType, 1);
        }
        $phpType = preg_replace('/\|Exception$/', '', $phpType);

        return match ($phpType) {
            'void'                  => 'void',
            'int', 'integer'        => 't_int',
            'float', 'double'       => 't_float',
            'string'                => 't_string',
            'bool', 'boolean'       => 't_bool',
            'array'                 => 't_array*',
            'object'                => 'void*',
            'callable', 'callback'  => 't_callback*',
            'null'                  => 'void*',
            'resource'              => 'void*',
            'never'                 => 'void',
            default                 => 'tphp_class_' . ltrim(str_replace('\\', '_', $phpType), '\\') . '*',
        };
    }

    /**
     * 节点 typ 字段（Type::idx()）→ C 类型字符串。
     * 用于从 FlatTypeChecker 标注的 typ 字段反推 C 类型。
     * 若 pointerLevel > 0，追加对应数量的 '*'。
     */
    private function typIdxToCType(int $typIdx, int $pointerLevel = 0): string
    {
        $base = match ($typIdx) {
            Type::IDX_INT       => 't_int',
            Type::IDX_FLOAT     => 't_float',
            Type::IDX_STRING    => 't_string',
            Type::IDX_BOOL      => 't_bool',
            Type::IDX_NULL      => 'void*',
            Type::IDX_ARRAY     => 't_array*',
            Type::IDX_MIXED     => 't_var',
            Type::IDX_OBJECT    => 'void*',
            Type::IDX_CALLBACK  => 't_callback*',
            Type::IDX_VOID      => 'void',
            Type::IDX_NEVER     => 'void',
            default             => 't_var',
        };
        if ($pointerLevel > 0) {
            $base .= str_repeat('*', $pointerLevel);
        }
        return $base;
    }

    // ═══════════════════════════════════════════════════════════════
    // 辅助
    // ═══════════════════════════════════════════════════════════════

    /**
     * 返回当前缩进字符串（4 空格 * indent）。
     */
    private function indentStr(): string
    {
        return str_repeat('    ', $this->indent);
    }
}
